Creat item
Berioul/my-capstone pull request #4
Opened 2022-03-27 10:30 UTC by Berioul

Front and Backend Control Service Repo  +  first Test

2022-03-27 11:07 UTC, sengsei commented
Moin Oualid ich glaube du musst erstmal deine Bugs fixen bevor jemand aproven kann

2022-03-27 11:19 UTC, Berioul commented
Ich habe gerade Probleme mit dem Port ich schau es mir nochmal an 
Danke dir !!

2022-03-28 06:56 UTC, crazySilvia approved these changes
Sieht soweit gut aus :)

2022-03-28 08:32 UTC, gossie requested changes
Ich habe einen Kommentar hinterlassen. Den müsstest du einmal fixen, damit der Build grün wird.

2022-03-28 08:32 UTC, gossie commented on frontend/src/App.tsx
>  import React, { useState, useEffect } from 'react';
Die werden beiden werden nicht verwendet und sollten gelöscht werden. Dann wird der Build auch grün.

2022-03-28 09:20 UTC, gossie approved these changes

2022-03-28 09:20 UTC, merged